local locale = GetLocale()

if locale == "deDE" then -- translated by dejaspeed
	LOSECONTROL = {
		["CC"]      = "CC",
		["Silence"] = "Stille",
		["Disarm"]  = "Entwaffnen",
		["Root"]    = "Wurzeln",
		["Snare"]   = "Bewegungseinschränkende Effekte",
		["PvE"]     = "PvE Überwachen",
		["Icon"] = {
			["player"] = "Spieler",
			["target"] = "Ziel",
			["focus"] = "Fokus",
			["party1"] = "Gruppenmitglied 1",
			["party2"] = "Gruppenmitglied 2",
			["party3"] = "Gruppenmitglied 3",
			["party4"] = "Gruppenmitglied 4",
			["arena1"] = "Arena Enemy 1",
			["arena2"] = "Arena Enemy 2",
			["arena3"] = "Arena Enemy 3",
			["arena4"] = "Arena Enemy 4",
			["arena5"] = "Arena Enemy 5",
		},
		["Enabled"] = "Aktivieren",
		["Icon Size"] = "Symbolgröße",
		["Opacity"] = "Transparenz",
		["Unlock"] = "Symbole entriegeln",
		[" (drag an icon to move)"] = " (Ziehen um Symbole zu bewegen)",
		["Disable OmniCC/CooldownCount Support"] = "Sperre OmniCC/CooldownCount",
		["Tracking"] = "Überwachte Effekte",
		["Minimum duration"] = "Minimale Überwachungsdauer",
		["Maximum duration"] = "Maximale Überwachungsdauer",
		["LoseControl reset."] = "LoseControl zurücksetzen.",
	}
elseif locale == "esES" or locale == "esMX" then -- translated by Babelfish :(
	LOSECONTROL = {
		["CC"]      = "CC",
		["Silence"] = "Silencio",
		["Disarm"]  = "Desarme",
		["Root"]    = "Inmovilice",
		["Snare"]   = "Trampa",
		["PvE"]     = "PvE",
		["Icon"] = {
			["player"] = "Jugador",
			["target"] = "Blanco",
			["focus"] = "Foco",
			["party1"] = "Partido 1",
			["party2"] = "Partido 2",
			["party3"] = "Partido 3",
			["party4"] = "Partido 4",
			["arena1"] = "Arena Enemy 1",
			["arena2"] = "Arena Enemy 2",
			["arena3"] = "Arena Enemy 3",
			["arena4"] = "Arena Enemy 4",
			["arena5"] = "Arena Enemy 5",
		},
		["Enabled"] = "Permitido",
		["Icon Size"] = "Tamaño del icono",
		["Opacity"] = "Opacidad",
		["Unlock"] = "Abra",
		[" (drag an icon to move)"] = " (arrastre el icono para moverse)",
		["Disable OmniCC/CooldownCount Support"] = "Neutralización OmniCC/CooldownCount",
		["Tracking"] = "Seguimiento",
		["Minimum duration"] = "Duración mínima",
		["Maximum duration"] = "Duración máxima",
		["LoseControl reset."] = "LoseControl reajuste.",
	}
elseif locale == "frFR" then -- translated by Babelfish :(
	LOSECONTROL = {
		["CC"]      = "CC",
		["Silence"] = "Silence",
		["Disarm"]  = "Désarmez",
		["Root"]    = "Immobilisez",
		["Snare"]   = "Piège",
		["PvE"]     = "PvE",
		["Icon"] = {
			["player"] = "Joueur",
			["target"] = "Cible",
			["focus"] = "Foyer",
			["party1"] = "Partie 1",
			["party2"] = "Partie 2",
			["party3"] = "Partie 3",
			["party4"] = "Partie 4",
			["arena1"] = "Arena Enemy 1",
			["arena2"] = "Arena Enemy 2",
			["arena3"] = "Arena Enemy 3",
			["arena4"] = "Arena Enemy 4",
			["arena5"] = "Arena Enemy 5",
		},
		["Enabled"] = "Permis",
		["Icon Size"] = "Taille d'icône",
		["Opacity"] = "Opacité",
		["Unlock"] = "Ouvrez",
		[" (drag an icon to move)"] = " (traînez l'icône pour se déplacer)",
		["Disable OmniCC/CooldownCount Support"] = "Débronchement OmniCC/CooldownCount",
		["Tracking"] = "Cheminement",
		["Minimum duration"] = "Durée minimum",
		["Maximum duration"] = "Durée maximum",
		["LoseControl reset."] = "LoseControl remise.",
	}
elseif locale == "koKR" then -- translated by Babelfish :(
	LOSECONTROL = {
		["CC"]      = "CC",
		["Silence"] = "침묵",
		["Disarm"]  = "기폭장치를 제거하십시오",
		["Root"]    = "고정시키십시오",
		["Snare"]   = "올가미",
		["PvE"]     = "PvE",
		["Icon"] = {
			["player"] = "선수",
			["target"] = "표적",
			["focus"] = "초점",
			["party1"] = "당 1",
			["party2"] = "당 2",
			["party3"] = "당 3",
			["party4"] = "당 4",
			["arena1"] = "Arena Enemy 1",
			["arena2"] = "Arena Enemy 2",
			["arena3"] = "Arena Enemy 3",
			["arena4"] = "Arena Enemy 4",
			["arena5"] = "Arena Enemy 5",
		},
		["Enabled"] = "가능하게 하는",
		["Icon Size"] = "아이콘 크기",
		["Opacity"] = "불투명",
		["Unlock"] = "자물쇠로 여십시오",
		[" (drag an icon to move)"] = " (움직이기 위하여 아이콘을 끄십시오)",
		["Disable OmniCC/CooldownCount Support"] = "무능 OmniCC/CooldownCount",
		["Tracking"] = "추적",
		["Minimum duration"] = "최소한도 내구",
		["Maximum duration"] = "최장 기간",
		["LoseControl reset."] = "LoseControl 리셋.",
	}
elseif locale == "ruRU" then -- translated by Termoshpuntik
	LOSECONTROL = {
		["CC"]      = "Потеря контроля",
		["Silence"] = "Антимагия",
		["Disarm"]  = "Разоружение",
		["Root"]    = "Удержание на месте",
		["Snare"]   = "Замедление",
		["PvE"]     = "PvE",
		["Icon"] = {
			["player"] = "Игрок",
			["target"] = "Цель",
			["focus"] = "Фокус",
			["party1"] = "1-й член группы",
			["party2"] = "2-й член группы",
			["party3"] = "3-й член группы",
			["party4"] = "4-й член группы",
			["arena1"] = "Arena Enemy 1",
			["arena2"] = "Arena Enemy 2",
			["arena3"] = "Arena Enemy 3",
			["arena4"] = "Arena Enemy 4",
			["arena5"] = "Arena Enemy 5",
		},
		["Enabled"] = "Включить",
		["Icon Size"] = "Размер значка",
		["Opacity"] = "Прозрачность",
		["Unlock"] = "Разблокировать",
		[" (drag an icon to move)"] = " (перемещайте значок с помошью курсора мыши)",
		["Disable OmniCC/CooldownCount Support"] = "Включить OmniCC/CooldownCount",
		["Tracking"] = "Отслеживать",
		["Minimum duration"] = "Минимальная продолжительность",
		["Maximum duration"] = "Максимальная продолжительность",
		["LoseControl reset."] = "Сброс настроек LoseControl.",
	}
elseif locale == "zhCN" or locale == "zhTW" then -- translated by 饺子
	LOSECONTROL = {
		["CC"]      = "控制类技能(e.g. 变形术,制裁之锤,致盲...)",
		["Silence"] = "沉默类技能",
		["Disarm"]  = "缴械类技能",
		["Root"]    = "定身类技能",
		["Snare"]   = "减速类技能",
		["PvE"]     = "PvE",
		["Icon"] = {
			["player"] = "球员",
			["target"] = "目标",
			["focus"] = "焦点",
			["party1"] = "党 1",
			["party2"] = "党 2",
			["party3"] = "党 3",
			["party4"] = "党 4",
			["arena1"] = "Arena Enemy 1",
			["arena2"] = "Arena Enemy 2",
			["arena3"] = "Arena Enemy 3",
			["arena4"] = "Arena Enemy 4",
			["arena5"] = "Arena Enemy 5",
		},
		["Enabled"] = "使能",
		["Icon Size"] = "大小",
		["Opacity"] = "透明度",
		["Unlock"] = "解除锁定",
		[" (drag an icon to move)"] = " (拖动图标移动)",
		["Disable OmniCC/CooldownCount Support"] = "屏蔽对 OmniCC/CooldownCount 的支持",
		["Tracking"] = "监视",
		["Minimum duration"] = "最小持续时间",
		["Maximum duration"] = "最大持续时间",
		["LoseControl reset."] = "LoseControl 已重置.",
	}
else
	LOSECONTROL = {
		["CC"]      = "CC",
		["Silence"] = "Silence",
		["Disarm"]  = "Disarm",
		["Root"]    = "Root",
		["Snare"]   = "Snare",
		["PvE"]     = "PvE",
		["Icon"] = {
			["player"] = "Player",
			["target"] = "Target",
			["focus"] = "Focus",
			["party1"] = "Party 1",
			["party2"] = "Party 2",
			["party3"] = "Party 3",
			["party4"] = "Party 4",
			["arena1"] = "Arena Enemy 1",
			["arena2"] = "Arena Enemy 2",
			["arena3"] = "Arena Enemy 3",
			["arena4"] = "Arena Enemy 4",
			["arena5"] = "Arena Enemy 5",
		},
		["Enabled"] = "Enabled",
		["Icon Size"] = "Icon Size",
		["Opacity"] = "Opacity",
		["Unlock"] = "Unlock",
		[" (drag an icon to move)"] = " (drag an icon to move)",
		["Disable OmniCC/CooldownCount Support"] = "Disable OmniCC/CooldownCount Support",
		["Tracking"] = "Tracking",
		["Minimum duration"] = "Minimum duration",
		["Maximum duration"] = "Maximum duration",
		["LoseControl reset."] = "LoseControl reset.",
	}
end
